import { Providers } from './providers';
import { rubik } from '@/theme/fonts';

import '../styles/globals.css';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} font-sans min-w-dvw m-0 flex flex-col min-h-dvh`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

